### ISSUE TITLE
Did you test it on face recognition?

### ISSUE THREAD

**Issue by IrvingShu** [RaviSoji/plda#45]

**Comment by RaviSoji** [comment]
You can find the results for facial recognition on p. 539, Fig. 4 of the [paper](https://github.com/RaviSoji/plda/blob/master/research_paper/Ioffe2006PLDA.pdf).

For me, the use cases were emotion, handwriting, and object recognition, where I was getting about ~35%, ~85%, and ~85% accuracy on cross validation tests with about 6-10 classes. If you are working with more classes, it might be wise to start with Fig. 4 of the paper to get a feel for how the recognition error scales.

Good luck!

**Comment by IrvingShu** [comment]
Thanks for your answer. I'm working on combining
CNN with JointBayers or PLDA, Did you try it with CNN feature?

**Comment by RaviSoji** [comment]
I am going to close this issue for now, but feel free to make a new one if you have updates or questions. You can also get in touch with me via my [website](https://ravisoji.com/about).
