### ISSUE TITLE
Is the implementation of Sec-3.1 in the paper added now?

### ISSUE THREAD

**Issue by ky941122** [RaviSoji/plda#51]
I want to use this repo to do a speaker recognition experiment. 
In my case, I have numbers of i-vectors from different speakers in training set. 
After I training the model, I want to use it to classify some vectors from unknonwn speakers belonging some other classes which are not in training set, and each class already has some labeled vectors. Just like the situation in the paper Sec-3.1 said.
But I can only find the way to classify these vectors to the same classes in training set by using .predict() method. So how can I fix this new classes problem.

**Comment by RaviSoji** [comment]
Check out `calc_same_diff_likelihood_ratio()` in [plda/plda/model.py](https://github.com/RaviSoji/plda/blob/master/plda/model.py).

Credit goes to @seandickert for implementing it. I will try to update the demo when if I get a this weekend.

**Comment by ky941122** [comment]
Got it! Thanks for replying.
