### ISSUE TITLE
cannot install through pip install plda

### ISSUE THREAD

**Issue by gzhu06** [RaviSoji/plda#55]
**Describe the bug**
After git clone, run "pip install plda", 
the error goes like: 
ERROR: Could not find a version that satisfies the requirement plda
ERROR: No matching distribution found for plda

**Comment by gzhu06** [comment]
solved by using pip install ./plda

**Comment by RaviSoji** [comment]
Thanks so much for this. I updated the installation instructions! 

Ravi B. Sojitra

**Comment by gzhu06** [comment]
You are welcome, nice works by the way.

**Comment by RaviSoji** [comment]
Thanks, I appreciate the compliment! 😀

Ravi B. Sojitra
